import { Container } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <Container maxW='1440px'>
      <Head>
        <title>Bit68 Task</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </Container>
  );
}
