import { Container } from "@chakra-ui/react";
import Head from "next/head";
import Header from "../components/Header";
import ImageSlider from "../components/ImageSlider";

export default function Home() {
  return (
    <Container maxW='1440px' p={0}>
      <Head>
        <title>Bit68 Task</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <ImageSlider />
    </Container>
  );
}
